# Generated by Django 4.2.5 on 2025-04-29 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField(default=0)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_todos', to='daily_tasks.priority')),
                ('task_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='daily_tasks.tasksheet')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('notify_before', models.CharField(choices=[('5', '5 دقائق'), ('15', '15 دقيقة'), ('30', '30 دقيقة'), ('60', 'ساعة واحدة'), ('1440', 'يوم واحد')], default='15', max_length=10)),
                ('notification_sent', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_reminders', to='daily_tasks.priority')),
                ('task_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='daily_tasks.tasksheet')),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_reminders', to='daily_tasks.todo')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.AddField(
            model_name='priority',
            name='task_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='daily_tasks.tasksheet'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notes', to='daily_tasks.priority')),
                ('task_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='daily_tasks.tasksheet')),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notes', to='daily_tasks.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='daily_tasks.tasksheet')),
            ],
        ),
    ]
